package net.quarix.qrx4j.samples.data.dao;

import net.quarix.qrx4j.samples.data.beans.Employee;
import net.quarix.qrx4j.samples.data.beans.meta.EmployeeDSSchema;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.IConfig;
import net.mystrobe.client.connector.IAppConnector;
import net.quarix.qrx4j.samples.data.beans.meta.EmployeeSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmemployee
 *		 doName: ttemployee
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmemployee", dsName="wicketds.server.dmemployee", dsId="daoemployee", daoId="ttemployee", isLocked=false)
public class EmployeeDataObject extends DataObjectAdaptor<Employee> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1391676695788L;
		
	@Generated
	@Deprecated
	public EmployeeDataObject (IAppConnector connector) {
		super(connector, new EmployeeDSSchema(), new EmployeeSchema());
	}

	@Generated
	public EmployeeDataObject (IConfig config, String appName) {
		super(config, appName, new EmployeeDSSchema(), new EmployeeSchema());
	}

	@Generated
	@Deprecated
	public EmployeeDataObject (IAppConnector connector, IDSSchema dsSchema, IDAOSchema<Employee> daoSchema ) {
		super(connector, dsSchema, daoSchema);
	}

	@Generated
	public EmployeeDataObject (IConfig config, String appName, IDSSchema dsSchema, IDAOSchema<Employee> daoSchema ) {
		super(config, appName, dsSchema, daoSchema);
	}
	
}

