package net.quarix.qrx4j.samples.data.dao;

import net.quarix.qrx4j.samples.data.beans.meta.OrderSchema;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.IConfig;
import net.quarix.qrx4j.samples.data.beans.Order;
import net.mystrobe.client.connector.IAppConnector;
import net.quarix.qrx4j.samples.data.beans.meta.OrderDSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmorder
 *		 doName: ttorder
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmorder", dsName="wicketds.server.dmorder", dsId="daoorder", daoId="ttorder", isLocked=false)
public class OrderDataObject extends DataObjectAdaptor<Order> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1391676325037L;
		
	@Generated
	@Deprecated
	public OrderDataObject (IAppConnector connector) {
		super(connector, new OrderDSSchema(), new OrderSchema());
	}

	@Generated
	public OrderDataObject (IConfig config, String appName) {
		super(config, appName, new OrderDSSchema(), new OrderSchema());
	}

	@Generated
	@Deprecated
	public OrderDataObject (IAppConnector connector, IDSSchema dsSchema, IDAOSchema<Order> daoSchema ) {
		super(connector, dsSchema, daoSchema);
	}

	@Generated
	public OrderDataObject (IConfig config, String appName, IDSSchema dsSchema, IDAOSchema<Order> daoSchema ) {
		super(config, appName, dsSchema, daoSchema);
	}
	
}

