package net.quarix.qrx4j.samples.data.beans;

import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmdepartment
 *		 doName: ttdepartment
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmdepartment", dsName="wicketds.server.dmdepartment", dsId="daodepartment", daoId="ttdepartment", isLocked=false)
public class Department  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1358516274153L;

	@Generated
	protected IDataSource dataSource;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected String deptcode;
	@Generated
	protected String deptname;

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Generated
	public String getDeptcode() {
		return deptcode;
	}

	@Generated
	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	@Generated
	public String getDeptname() {
		return deptname;
	}

	@Generated
	public IDataSource getDataSource() {
		return dataSource;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Generated
	public void detach() {		
	}

	@Override
	public String toString() {
		return  " Department  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", deptcode =" + deptcode + "\n" + 
	   ", deptname =" + deptname + "\n" + 
	  "] " ;
	}
	
	
}

