package net.quarix.qrx4j.samples.data.beans.meta;

import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmdepartment
 *		 doName: ttdepartment
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmdepartment", dsName="wicketds.server.dmdepartment", dsId="daodepartment", isLocked=false)
public class DepartmentDSSchema extends DSSchema {

	@Generated
	public DepartmentDSSchema() {
		id = "daodepartment";
		batchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmdepartment";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttdepartment", new DepartmentSchema());
	}
	
}

