package net.quarix.qrx4j.samples.data.beans.meta;

import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmpurchaseorder
 *		 doName: ttpurchaseorder
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmpurchaseorder", dsName="wicketds.server.dmpurchaseorder", dsId="daopurchaseorder", isLocked=false)
public class PurchaseOrderDSSchema extends DSSchema {

	@Generated
	public PurchaseOrderDSSchema() {
		id = "daopurchaseorder";
		batchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmpurchaseorder";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttpurchaseorder", new PurchaseOrderSchema());
	}
	
}

