@Generated
private static final long serialVersionUID = $serialVersionUID$L;

@Generated
protected IDataSource dataSource;

$fields:{f|$f$}; separator="\n"$

$methods:{m|$m$}; separator="\n\n"$

@Generated
public IDataSource getDataSource() {
	return dataSource;
}

@Generated
public String getRowId() {
	return $rowid$;
}

@Generated
public void detach() {		
}

@Override
public String toString() {
	return $toString$;
}
