package net.quarix.qrx4j.samples.data.beans;

import java.math.BigDecimal;
import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmcustomer
 *		 doName: ttcustomer
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmcustomer", dsName="wicketds.server.dmcustomer", dsId="daocustomer", daoId="ttcustomer", isLocked=false)
public class Customer  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1355838783063L;

	@Generated
	protected IDataSource dataSource;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected String address;
	@Generated
	protected String address2;
	@Generated
	protected BigDecimal balance;
	@Generated
	protected String city;
	@Generated
	protected String comments;
	@Generated
	protected String contact;
	@Generated
	protected String country;
	@Generated
	protected BigDecimal creditlimit;
	@Generated
	protected Integer custnum;
	@Generated
	protected Integer discount;
	@Generated
	protected String emailaddress;
	@Generated
	protected String fax;
	@Generated
	protected String name;
	@Generated
	protected String phone;
	@Generated
	protected String postalcode;
	@Generated
	protected String salesrep;
	@Generated
	protected String state;
	@Generated
	protected String terms;
	@Generated
	protected String statename;
	@Generated
	protected String salesrepname;

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setAddress(String address) {
		this.address = address;
	}

	@Generated
	public String getAddress() {
		return address;
	}

	@Generated
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Generated
	public String getAddress2() {
		return address2;
	}

	@Generated
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Generated
	public BigDecimal getBalance() {
		return balance;
	}

	@Generated
	public void setCity(String city) {
		this.city = city;
	}

	@Generated
	public String getCity() {
		return city;
	}

	@Generated
	public void setComments(String comments) {
		this.comments = comments;
	}

	@Generated
	public String getComments() {
		return comments;
	}

	@Generated
	public void setContact(String contact) {
		this.contact = contact;
	}

	@Generated
	public String getContact() {
		return contact;
	}

	@Generated
	public void setCountry(String country) {
		this.country = country;
	}

	@Generated
	public String getCountry() {
		return country;
	}

	@Generated
	public void setCreditlimit(BigDecimal creditlimit) {
		this.creditlimit = creditlimit;
	}

	@Generated
	public BigDecimal getCreditlimit() {
		return creditlimit;
	}

	@Generated
	public void setCustnum(Integer custnum) {
		this.custnum = custnum;
	}

	@Generated
	public Integer getCustnum() {
		return custnum;
	}

	@Generated
	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	@Generated
	public Integer getDiscount() {
		return discount;
	}

	@Generated
	public void setEmailaddress(String emailaddress) {
		this.emailaddress = emailaddress;
	}

	@Generated
	public String getEmailaddress() {
		return emailaddress;
	}

	@Generated
	public void setFax(String fax) {
		this.fax = fax;
	}

	@Generated
	public String getFax() {
		return fax;
	}

	@Generated
	public void setName(String name) {
		this.name = name;
	}

	@Generated
	public String getName() {
		return name;
	}

	@Generated
	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Generated
	public String getPhone() {
		return phone;
	}

	@Generated
	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	@Generated
	public String getPostalcode() {
		return postalcode;
	}

	@Generated
	public void setSalesrep(String salesrep) {
		this.salesrep = salesrep;
	}

	@Generated
	public String getSalesrep() {
		return salesrep;
	}

	@Generated
	public void setState(String state) {
		this.state = state;
	}

	@Generated
	public String getState() {
		return state;
	}

	@Generated
	public void setTerms(String terms) {
		this.terms = terms;
	}

	@Generated
	public String getTerms() {
		return terms;
	}
	
	@Generated
	public String getStatename() {
		return statename;
	}

	@Generated
	public void setStatename(String statename) {
		this.statename = statename;
	}

	@Generated
	public String getSalesrepname() {
		return salesrepname;
	}

	@Generated
	public void setSalesrepname(String salesrepname) {
		this.salesrepname = salesrepname;
	}

	@Generated
	public IDataSource getDataSource() {
		return dataSource;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Generated
	public void detach() {		
	}

	@Override
	public String toString() {
		return  " Customer  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", address =" + address + "\n" + 
	   ", address2 =" + address2 + "\n" + 
	   ", balance =" + balance + "\n" + 
	   ", city =" + city + "\n" + 
	   ", comments =" + comments + "\n" + 
	   ", contact =" + contact + "\n" + 
	   ", country =" + country + "\n" + 
	   ", creditlimit =" + creditlimit + "\n" + 
	   ", custnum =" + custnum + "\n" + 
	   ", discount =" + discount + "\n" + 
	   ", emailaddress =" + emailaddress + "\n" + 
	   ", fax =" + fax + "\n" + 
	   ", name =" + name + "\n" + 
	   ", phone =" + phone + "\n" + 
	   ", postalcode =" + postalcode + "\n" + 
	   ", salesrep =" + salesrep + "\n" + 
	   ", state =" + state + "\n" + 
	   ", terms =" + terms + "\n" + 
	  "] " ;
	}
	
	
}

