package net.quarix.qrx4j.samples.data.beans;

import java.util.Date;
import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.impl.DAOSchema;
import net.quarix.qrx4j.samples.data.beans.meta.PurchaseOrderDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.PurchaseOrderSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmpurchaseorder
 *		 doName: ttpurchaseorder
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmpurchaseorder", dsName="wicketds.server.dmpurchaseorder", dsId="daopurchaseorder", daoId="ttpurchaseorder", isLocked=false)
public class PurchaseOrder  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1391676813160L;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected Integer ponum;
	@Generated
	protected Date dateentered;
	@Generated
	protected Date receivedate;
	@Generated
	protected String postatus;
	@Generated
	protected Integer supplieridnum;

	@Generated
	public static Class<? extends IDSSchema> getDSSchemaClass() {
		return PurchaseOrderDSSchema.class;
	}

	@Generated	
	public static Class<? extends DAOSchema<PurchaseOrder>> getDAOSchemaClass() {
		return PurchaseOrderSchema.class;
	}

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setPonum(Integer ponum) {
		this.ponum = ponum;
	}

	@Generated
	public Integer getPonum() {
		return ponum;
	}

	@Generated
	public void setDateentered(Date dateentered) {
		this.dateentered = dateentered;
	}

	@Generated
	public Date getDateentered() {
		return dateentered;
	}

	@Generated
	public void setReceivedate(Date receivedate) {
		this.receivedate = receivedate;
	}

	@Generated
	public Date getReceivedate() {
		return receivedate;
	}

	@Generated
	public void setPostatus(String postatus) {
		this.postatus = postatus;
	}

	@Generated
	public String getPostatus() {
		return postatus;
	}

	@Generated
	public void setSupplieridnum(Integer supplieridnum) {
		this.supplieridnum = supplieridnum;
	}

	@Generated
	public Integer getSupplieridnum() {
		return supplieridnum;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Override
	public String toString() {
		return  " PurchaseOrder  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", ponum =" + ponum + "\n" + 
	   ", dateentered =" + dateentered + "\n" + 
	   ", receivedate =" + receivedate + "\n" + 
	   ", postatus =" + postatus + "\n" + 
	   ", supplieridnum =" + supplieridnum + "\n" + 
	  "] " ;
	}
	
}

