package net.quarix.qrx4j.samples.data.beans;

import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.impl.DAOSchema;
import net.quarix.qrx4j.samples.data.beans.meta.SalesRepDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.SalesRepSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmsalesrep
 *		 doName: ttsalesrep
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmsalesrep", dsName="wicketds.server.dmsalesrep", dsId="daosalesrep", daoId="ttsalesrep", isLocked=false)
public class SalesRep  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1391676865708L;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected String salesrep;
	@Generated
	protected String repname;
	@Generated
	protected String region;

	@Generated
	public static Class<? extends IDSSchema> getDSSchemaClass() {
		return SalesRepDSSchema.class;
	}

	@Generated	
	public static Class<? extends DAOSchema<SalesRep>> getDAOSchemaClass() {
		return SalesRepSchema.class;
	}

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setSalesrep(String salesrep) {
		this.salesrep = salesrep;
	}

	@Generated
	public String getSalesrep() {
		return salesrep;
	}

	@Generated
	public void setRepname(String repname) {
		this.repname = repname;
	}

	@Generated
	public String getRepname() {
		return repname;
	}

	@Generated
	public void setRegion(String region) {
		this.region = region;
	}

	@Generated
	public String getRegion() {
		return region;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Override
	public String toString() {
		return  " SalesRep  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", salesrep =" + salesrep + "\n" + 
	   ", repname =" + repname + "\n" + 
	   ", region =" + region + "\n" + 
	  "] " ;
	}
	
}

