package net.quarix.qrx4j.samples.data.dao;

import net.quarix.qrx4j.samples.data.beans.Employee;
import net.quarix.qrx4j.samples.data.beans.meta.EmployeeDSSchema;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.quarix.qrx4j.samples.data.beans.meta.EmployeeSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmemployee
 *		 doName: ttemployee
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmemployee", dsName="wicketds.server.dmemployee", dsId="daoemployee", daoId="ttemployee", isLocked=false)
public class EmployeeDataObject extends DataObjectAdaptor<Employee> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1358517013768L;

	@Generated
	@Override
	protected void assignValues () {
		this.schema = new EmployeeSchema();
		this.defaultDSSchema= new EmployeeDSSchema();  
	}
	
	
}

