package net.quarix.qrx4j.samples.data.dao;

import net.mystrobe.client.connector.quarixbackend.Generated;
import net.quarix.qrx4j.samples.data.beans.meta.ItemSchema;
import net.quarix.qrx4j.samples.data.beans.Item;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.quarix.qrx4j.samples.data.beans.meta.ItemDSSchema;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmitem
 *		 doName: ttitem
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmitem", dsName="wicketds.server.dmitem", dsId="daitem", daoId="ttitem", isLocked=false)
public class ItemDataObject extends DataObjectAdaptor<Item> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1357832969172L;

	@Generated
	@Override
	protected void assignValues () {
		this.schema = new ItemSchema();
		this.defaultDSSchema= new ItemDSSchema();  
	}
	
	
}

