package net.quarix.qrx4j.samples.data.dao;

import java.io.Serializable;

import net.mystrobe.client.DataObjectAdaptor;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.quarix.qrx4j.samples.data.beans.Order;
import net.quarix.qrx4j.samples.data.beans.meta.OrderDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.OrderSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dtordordline
 *		 doName: ttorder
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dtordordline", dsName="wicketds.server.dtordordline", dsId="daordordline", daoId="ttorder", isLocked=false)
public class OrderDataObject extends DataObjectAdaptor<Order> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1359137283241L;

	@Generated
	@Override
	protected void assignValues () {
		this.schema = new OrderSchema();
		this.defaultDSSchema= new OrderDSSchema();  
	}
}

