package net.quarix.qrx4j.samples.data.dao;

import net.quarix.qrx4j.samples.data.beans.meta.StateSchema;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.quarix.qrx4j.samples.data.beans.State;
import net.quarix.qrx4j.samples.data.beans.meta.StateDSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmstate
 *		 doName: ttstate
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmstate", dsName="wicketds.server.dmstate", dsId="daostate", daoId="ttstate", isLocked=false)
public class StateDataObject extends DataObjectAdaptor<State> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1358517568376L;

	@Generated
	@Override
	protected void assignValues () {
		this.schema = new StateSchema();
		this.defaultDSSchema= new StateDSSchema();  
	}
	
	
}

