package net.quarix.qrx4j.samples.data.beans.meta;

import java.util.Collections;
import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmsalesrep
 *		 doName: ttsalesrep
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmsalesrep", dsName="wicketds.server.dmsalesrep", dsId="daosalesrep", isLocked=false)
public class SalesRepDSSchema extends DSSchema {

	@Generated
	public SalesRepDSSchema() {
		id = "daosalesrep";
		bathchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmsalesrep";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttsalesrep", new SalesRepSchema());
	}
	
	
}

