package net.quarix.qrx4j.samples.data.beans.meta;

import java.util.Collections;
import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmcustomer
 *		 doName: ttcustomer
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmcustomer", dsName="wicketds.server.dmcustomer", dsId="daocustomer", isLocked=false)
public class CustomerDSSchema extends DSSchema {

	@Generated
	public CustomerDSSchema() {
		id = "daocustomer";
		bathchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmcustomer";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttcustomer", new CustomerSchema());
	}
	
	
}

