package net.quarix.qrx4j.samples.data.beans.meta;

import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmitem
 *		 doName: ttitem
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmitem", dsName="wicketds.server.dmitem", dsId="daitem", isLocked=false)
public class ItemDSSchema extends DSSchema {

	@Generated
	public ItemDSSchema() {
		id = "daitem";
		batchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmitem";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttitem", new ItemSchema());
	}
	
}

