package net.quarix.qrx4j.samples.data.beans.meta;

import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmorderline
 *		 doName: ttorderline
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmorderline", dsName="wicketds.server.dmorderline", dsId="daoorderline", isLocked=false)
public class OrderLineDSSchema extends DSSchema {

	@Generated
	public OrderLineDSSchema() {
		id = "daoorderline";
		batchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmorderline";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttorderline", new OrderLineSchema());
	}
	
}

