package net.quarix.qrx4j.samples.data.beans.meta;

import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dtordordline
 *		 doName: ttorder
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dtordordline", dsName="wicketds.server.dtordordline", dsId="daordordline", isLocked=false)
public class OrderInfoDSSchema extends DSSchema {

	@Generated
	public OrderInfoDSSchema() {
		id = "daordordline";
		batchSize = 0;
		margin = 5;
		urn = "wicketds.server.dtordordline";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttorderline", new OrderLineSchema());
		daoMap.put("ttorder", new OrderSchema());
	}
	
}

