/**
 * Copyright (C) 2010-2011 TVH Group NV. <kalman.tiboldi@tvh.com>
 *
 * This file is part of the MyStroBe project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * 		http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package net.mystrobe.client.connector.quarixbackend.datatypes;

import net.mystrobe.client.IDataBean;
import net.mystrobe.client.IDataSource;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;

/**
 * 
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 * 
 * Used parameters: appName: wicketds dsName: server.salesrep doName: tt-salesrep
 * 
 */

@GeneratorMeta(appName="wicketds", urn="server.salesrep", dsName="server.salesrep", dsId="dsSalesRep", daoId="tt-salesrep", isLocked=false)
public class SalesRepSalesrep  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1308428582001L;

	@Generated
	protected IDataSource dataSource;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected String salesrep;
	@Generated
	protected String repname;
	@Generated
	protected String region;
	@Generated
	protected Integer monthquota_1;
	@Generated
	protected Integer monthquota_2;
	@Generated
	protected Integer monthquota_3;
	@Generated
	protected Integer monthquota_4;
	@Generated
	protected Integer monthquota_5;
	@Generated
	protected Integer monthquota_6;
	@Generated
	protected Integer monthquota_7;
	@Generated
	protected Integer monthquota_8;
	@Generated
	protected Integer monthquota_9;
	@Generated
	protected Integer monthquota_10;
	@Generated
	protected Integer monthquota_11;
	@Generated
	protected Integer monthquota_12;

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSalesrep(String salesrep) {
		this.salesrep = salesrep;
	}

	@Generated
	public String getSalesrep() {
		return salesrep;
	}

	@Generated
	public void setRepname(String repname) {
		this.repname = repname;
	}

	@Generated
	public String getRepname() {
		return repname;
	}

	@Generated
	public void setRegion(String region) {
		this.region = region;
	}

	@Generated
	public String getRegion() {
		return region;
	}

	@Generated
	public void setMonthquota_1(Integer monthquota_1) {
		this.monthquota_1 = monthquota_1;
	}

	@Generated
	public Integer getMonthquota_1() {
		return monthquota_1;
	}

	@Generated
	public void setMonthquota_2(Integer monthquota_2) {
		this.monthquota_2 = monthquota_2;
	}

	@Generated
	public Integer getMonthquota_2() {
		return monthquota_2;
	}

	@Generated
	public void setMonthquota_3(Integer monthquota_3) {
		this.monthquota_3 = monthquota_3;
	}

	@Generated
	public Integer getMonthquota_3() {
		return monthquota_3;
	}

	@Generated
	public void setMonthquota_4(Integer monthquota_4) {
		this.monthquota_4 = monthquota_4;
	}

	@Generated
	public Integer getMonthquota_4() {
		return monthquota_4;
	}

	@Generated
	public void setMonthquota_5(Integer monthquota_5) {
		this.monthquota_5 = monthquota_5;
	}

	@Generated
	public Integer getMonthquota_5() {
		return monthquota_5;
	}

	@Generated
	public void setMonthquota_6(Integer monthquota_6) {
		this.monthquota_6 = monthquota_6;
	}

	@Generated
	public Integer getMonthquota_6() {
		return monthquota_6;
	}

	@Generated
	public void setMonthquota_7(Integer monthquota_7) {
		this.monthquota_7 = monthquota_7;
	}

	@Generated
	public Integer getMonthquota_7() {
		return monthquota_7;
	}

	@Generated
	public void setMonthquota_8(Integer monthquota_8) {
		this.monthquota_8 = monthquota_8;
	}

	@Generated
	public Integer getMonthquota_8() {
		return monthquota_8;
	}

	@Generated
	public void setMonthquota_9(Integer monthquota_9) {
		this.monthquota_9 = monthquota_9;
	}

	@Generated
	public Integer getMonthquota_9() {
		return monthquota_9;
	}

	@Generated
	public void setMonthquota_10(Integer monthquota_10) {
		this.monthquota_10 = monthquota_10;
	}

	@Generated
	public Integer getMonthquota_10() {
		return monthquota_10;
	}

	@Generated
	public void setMonthquota_11(Integer monthquota_11) {
		this.monthquota_11 = monthquota_11;
	}

	@Generated
	public Integer getMonthquota_11() {
		return monthquota_11;
	}

	@Generated
	public void setMonthquota_12(Integer monthquota_12) {
		this.monthquota_12 = monthquota_12;
	}

	@Generated
	public Integer getMonthquota_12() {
		return monthquota_12;
	}

	@Generated
	public IDataSource getDataSource() {
		return dataSource;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Generated
	public void detach() {		
	}
	
	
}

