package net.quarix.qrx4j.samples.data.beans;

import java.util.Date;
import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.impl.DAOSchema;
import net.quarix.qrx4j.samples.data.beans.meta.EmployeeDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.EmployeeSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmemployee
 *		 doName: ttemployee
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmemployee", dsName="wicketds.server.dmemployee", dsId="daoemployee", daoId="ttemployee", isLocked=false)
public class Employee  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1391676695815L;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected Integer empnum;
	@Generated
	protected String address;
	@Generated
	protected String address2;
	@Generated
	protected Date birthdate;
	@Generated
	protected String city;
	@Generated
	protected String deptcode;
	@Generated
	protected String firstname;
	@Generated
	protected String lastname;
	@Generated
	protected String homephone;
	@Generated
	protected String workphone;
	@Generated
	protected String position;
	@Generated
	protected Date startdate;
	@Generated
	protected String postalcode;
	@Generated
	protected String state;
	@Generated
	protected String deptname;
	@Generated
	protected String statename;

	@Generated
	public static Class<? extends IDSSchema> getDSSchemaClass() {
		return EmployeeDSSchema.class;
	}

	@Generated	
	public static Class<? extends DAOSchema<Employee>> getDAOSchemaClass() {
		return EmployeeSchema.class;
	}

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setEmpnum(Integer empnum) {
		this.empnum = empnum;
	}

	@Generated
	public Integer getEmpnum() {
		return empnum;
	}

	@Generated
	public void setAddress(String address) {
		this.address = address;
	}

	@Generated
	public String getAddress() {
		return address;
	}

	@Generated
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Generated
	public String getAddress2() {
		return address2;
	}

	@Generated
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Generated
	public Date getBirthdate() {
		return birthdate;
	}

	@Generated
	public void setCity(String city) {
		this.city = city;
	}

	@Generated
	public String getCity() {
		return city;
	}

	@Generated
	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	@Generated
	public String getDeptcode() {
		return deptcode;
	}

	@Generated
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Generated
	public String getFirstname() {
		return firstname;
	}

	@Generated
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Generated
	public String getLastname() {
		return lastname;
	}

	@Generated
	public void setHomephone(String homephone) {
		this.homephone = homephone;
	}

	@Generated
	public String getHomephone() {
		return homephone;
	}

	@Generated
	public void setWorkphone(String workphone) {
		this.workphone = workphone;
	}

	@Generated
	public String getWorkphone() {
		return workphone;
	}

	@Generated
	public void setPosition(String position) {
		this.position = position;
	}

	@Generated
	public String getPosition() {
		return position;
	}

	@Generated
	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Generated
	public Date getStartdate() {
		return startdate;
	}

	@Generated
	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	@Generated
	public String getPostalcode() {
		return postalcode;
	}

	@Generated
	public void setState(String state) {
		this.state = state;
	}

	@Generated
	public String getState() {
		return state;
	}

	@Generated
	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	@Generated
	public String getDeptname() {
		return deptname;
	}

	@Generated
	public void setStatename(String statename) {
		this.statename = statename;
	}

	@Generated
	public String getStatename() {
		return statename;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Override
	public String toString() {
		return  " Employee  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", empnum =" + empnum + "\n" + 
	   ", address =" + address + "\n" + 
	   ", address2 =" + address2 + "\n" + 
	   ", birthdate =" + birthdate + "\n" + 
	   ", city =" + city + "\n" + 
	   ", deptcode =" + deptcode + "\n" + 
	   ", firstname =" + firstname + "\n" + 
	   ", lastname =" + lastname + "\n" + 
	   ", homephone =" + homephone + "\n" + 
	   ", workphone =" + workphone + "\n" + 
	   ", position =" + position + "\n" + 
	   ", startdate =" + startdate + "\n" + 
	   ", postalcode =" + postalcode + "\n" + 
	   ", state =" + state + "\n" + 
	   ", deptname =" + deptname + "\n" + 
	   ", statename =" + statename + "\n" + 
	  "] " ;
	}
	
}

