package net.quarix.qrx4j.samples.data.beans;

import java.math.BigDecimal;
import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.impl.DAOSchema;
import net.quarix.qrx4j.samples.data.beans.meta.ItemDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.ItemSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmitem
 *		 doName: ttitem
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmitem", dsName="wicketds.server.dmitem", dsId="daitem", daoId="ttitem", isLocked=false)
public class Item  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1391676742849L;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected String catdescription;
	@Generated
	protected String itemname;
	@Generated
	protected Integer itemnum;
	@Generated
	protected BigDecimal price;
	@Generated
	protected BigDecimal weight;
	@Generated
	protected String category1;
	@Generated
	protected String category2;

	@Generated
	public static Class<? extends IDSSchema> getDSSchemaClass() {
		return ItemDSSchema.class;
	}

	@Generated	
	public static Class<? extends DAOSchema<Item>> getDAOSchemaClass() {
		return ItemSchema.class;
	}

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setCatdescription(String catdescription) {
		this.catdescription = catdescription;
	}

	@Generated
	public String getCatdescription() {
		return catdescription;
	}

	@Generated
	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Generated
	public String getItemname() {
		return itemname;
	}

	@Generated
	public void setItemnum(Integer itemnum) {
		this.itemnum = itemnum;
	}

	@Generated
	public Integer getItemnum() {
		return itemnum;
	}

	@Generated
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Generated
	public BigDecimal getPrice() {
		return price;
	}

	@Generated
	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Generated
	public BigDecimal getWeight() {
		return weight;
	}

	@Generated
	public void setCategory1(String category1) {
		this.category1 = category1;
	}

	@Generated
	public String getCategory1() {
		return category1;
	}

	@Generated
	public void setCategory2(String category2) {
		this.category2 = category2;
	}

	@Generated
	public String getCategory2() {
		return category2;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Override
	public String toString() {
		return  " Item  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", catdescription =" + catdescription + "\n" + 
	   ", itemname =" + itemname + "\n" + 
	   ", itemnum =" + itemnum + "\n" + 
	   ", price =" + price + "\n" + 
	   ", weight =" + weight + "\n" + 
	   ", category1 =" + category1 + "\n" + 
	   ", category2 =" + category2 + "\n" + 
	  "] " ;
	}
	
}

