package net.quarix.qrx4j.samples.data.dao;

import net.mystrobe.client.connector.quarixbackend.Generated;
import net.quarix.qrx4j.samples.data.beans.Customer;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import net.quarix.qrx4j.samples.data.beans.meta.CustomerDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.CustomerSchema;
import java.io.Serializable;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmcustomer
 *		 doName: ttcustomer
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmcustomer", dsName="wicketds.server.dmcustomer", dsId="daocustomer", daoId="ttcustomer", isLocked=false)
public class CustomerDataObject extends DataObjectAdaptor<Customer> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1355838782878L;

	@Generated
	@Override
	protected void assignValues () {
		this.schema = new CustomerSchema();
		this.defaultDSSchema= new CustomerDSSchema();  
	}
	
	
}

