package net.quarix.qrx4j.samples.data.dao;

import java.io.Serializable;

import net.mystrobe.client.DataObjectAdaptor;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.quarix.qrx4j.samples.data.beans.OrderLine;
import net.quarix.qrx4j.samples.data.beans.meta.OrderLineDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.OrderLineSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dtordordline
 *		 doName: ttorder
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dtordordline", dsName="wicketds.server.dtordordline", dsId="daordordline", daoId="ttorderline", isLocked=false)
public class OrderLineDataObject extends DataObjectAdaptor<OrderLine> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1359137283105L;

	@Generated
	@Override
	protected void assignValues () {
		this.schema = new OrderLineSchema();
		this.defaultDSSchema= new OrderLineDSSchema();  
	}
	
	
}

