package net.mystrobe.client.connector.quarixbackend.datatypes;

import net.mystrobe.client.IDataSource;
import net.mystrobe.client.IDataBean;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmstate
 *		 doName: ttstate
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmstate", dsName="wicketds.server.dmstate", dsId="daostate", daoId="ttstate", isLocked=false)
public class State  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1384439077111L;

	@Generated
	protected IDataSource dataSource;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected Integer sortorder;
	@Generated
	protected String region;
	@Generated
	protected String statecode;
	@Generated
	protected String statename;

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Generated
	public Integer getSortorder() {
		return sortorder;
	}

	@Generated
	public void setRegion(String region) {
		this.region = region;
	}

	@Generated
	public String getRegion() {
		return region;
	}

	@Generated
	public void setStatecode(String statecode) {
		this.statecode = statecode;
	}

	@Generated
	public String getStatecode() {
		return statecode;
	}

	@Generated
	public void setStatename(String statename) {
		this.statename = statename;
	}

	@Generated
	public String getStatename() {
		return statename;
	}

	@Generated
	public IDataSource getDataSource() {
		return dataSource;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Generated
	public void detach() {		
	}

	@Override
	public String toString() {
		return  " State  [  " +  " rowid =" + rowid + "\n" +  
	    ", rowstate =" + rowstate + "\n" + 
	   ", sortorder =" + sortorder + "\n" + 
	   ", region =" + region + "\n" + 
	   ", statecode =" + statecode + "\n" + 
	   ", statename =" + statename + "\n" + 
	  "] " ;
	}
	
	
}

