package net.mystrobe.client.connector.quarixbackend.datatypes;

import net.mystrobe.client.DataObjectAdaptor;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;

import net.mystrobe.client.connector.IAppConnector;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmstate
 *		 doName: ttstate
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmstate", dsName="wicketds.server.dmstate", dsId="daostate", daoId="ttstate", isLocked=false)
public class StateDataObject extends DataObjectAdaptor<State> implements Serializable {

	private static final long serialVersionUID = 1384439077064L;
	
	public StateDataObject(IAppConnector connector) {
		super(connector, new StateDSSchema(), new StateSchema());
	}	
	
}

