package net.quarix.qrx4j.samples.data.beans.meta;

import java.util.Collections;
import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmemployee
 *		 doName: ttemployee
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmemployee", dsName="wicketds.server.dmemployee", dsId="daoemployee", isLocked=false)
public class EmployeeDSSchema extends DSSchema {

	@Generated
	public EmployeeDSSchema() {
		id = "daoemployee";
		bathchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmemployee";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttemployee", new EmployeeSchema());
	}
	
	
}

