package net.quarix.qrx4j.samples.data.beans.meta;

import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.impl.DSSchema;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmorder
 *		 doName: ttorder
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmorder", dsName="wicketds.server.dmorder", dsId="daoorder", isLocked=false)
public class OrderDSSchema extends DSSchema {

	@Generated
	public OrderDSSchema() {
		id = "daoorder";
		bathchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmorder";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttorder", new OrderSchema());
	}
	
	
}

