package net.quarix.qrx4j.samples.data.beans.meta;

import java.util.Collections;
import net.mystrobe.client.impl.DSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.connector.quarixbackend.Generated;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: qrxexmpl
 *		 dsName: wicketds.server.dmpurchaseorder
 *		 doName: ttpurchaseorder
 *
 */

@GeneratorMeta(appName="qrxexmpl", urn="wicketds.server.dmpurchaseorder", dsName="wicketds.server.dmpurchaseorder", dsId="daopurchaseorder", isLocked=false)
public class PurchaseOrderDSSchema extends DSSchema {

	@Generated
	public PurchaseOrderDSSchema() {
		id = "daopurchaseorder";
		bathchSize = 0;
		margin = 5;
		urn = "wicketds.server.dmpurchaseorder";
		hasFilteredChildren = true;

		loadRelations(new String[] {});

		daoMap.put("ttpurchaseorder", new PurchaseOrderSchema());
	}
	
	
}

