/**
 * Copyright (C) 2010-2011 TVH Group NV. <kalman.tiboldi@tvh.com>
 *
 * This file is part of the MyStroBe project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * 		http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package net.mystrobe.client.connector.quarixbackend.datatypes;

import net.mystrobe.client.IDataBean;
import net.mystrobe.client.IDataSource;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;

/**
 * 
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 * 
 * Used parameters: appName: wicketds dsName: server.state doName: tt-state
 * 
 */

@GeneratorMeta(appName="wicketds", urn="server.state", dsName="server.state", dsId="dsState", daoId="tt-state", isLocked=false)
public class StateState  implements IDataBean {

	@Generated
	private static final long serialVersionUID = 1308428585655L;

	@Generated
	protected IDataSource dataSource;

	@Generated
	protected String rowid;
	@Generated
	protected Integer rowstate;
	@Generated
	protected String state;
	@Generated
	protected String statename;
	@Generated
	protected String region;

	@Generated
	public void setRowid(String rowid) {
		this.rowid = rowid;
	}

	@Generated
	public void setRowstate(Integer rowstate) {
		this.rowstate = rowstate;
	}

	@Generated
	public Integer getRowstate() {
		return rowstate;
	}

	@Generated
	public void setState(String state) {
		this.state = state;
	}

	@Generated
	public String getState() {
		return state;
	}

	@Generated
	public void setStatename(String statename) {
		this.statename = statename;
	}

	@Generated
	public String getStatename() {
		return statename;
	}

	@Generated
	public void setRegion(String region) {
		this.region = region;
	}

	@Generated
	public String getRegion() {
		return region;
	}

	@Generated
	public IDataSource getDataSource() {
		return dataSource;
	}

	@Generated
	public String getRowId() {
		return rowid;
	}

	@Generated
	public void detach() {		
	}
	
	
}

