package net.quarix.qrx4j.samples.data.dao;

import net.mystrobe.client.connector.quarixbackend.Generated;
import net.quarix.qrx4j.samples.data.beans.Department;
import net.mystrobe.client.connector.IConfig;
import net.mystrobe.client.connector.IAppConnector;
import net.quarix.qrx4j.samples.data.beans.meta.DepartmentDSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.IDSSchema;
import net.quarix.qrx4j.samples.data.beans.meta.DepartmentSchema;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmdepartment
 *		 doName: ttdepartment
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmdepartment", dsName="wicketds.server.dmdepartment", dsId="daodepartment", daoId="ttdepartment", isLocked=false)
public class DepartmentDataObject extends DataObjectAdaptor<Department> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1391676632688L;
		
	@Generated
	@Deprecated
	public DepartmentDataObject (IAppConnector connector) {
		super(connector, new DepartmentDSSchema(), new DepartmentSchema());
	}

	@Generated
	public DepartmentDataObject (IConfig config, String appName) {
		super(config, appName, new DepartmentDSSchema(), new DepartmentSchema());
	}

	@Generated
	@Deprecated
	public DepartmentDataObject (IAppConnector connector, IDSSchema dsSchema, IDAOSchema<Department> daoSchema ) {
		super(connector, dsSchema, daoSchema);
	}

	@Generated
	public DepartmentDataObject (IConfig config, String appName, IDSSchema dsSchema, IDAOSchema<Department> daoSchema ) {
		super(config, appName, dsSchema, daoSchema);
	}
	
}

