package net.quarix.qrx4j.samples.data.dao;

import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.IConfig;
import net.quarix.qrx4j.samples.data.beans.meta.ItemSchema;
import net.quarix.qrx4j.samples.data.beans.Item;
import net.mystrobe.client.connector.IAppConnector;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.quarix.qrx4j.samples.data.beans.meta.ItemDSSchema;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmitem
 *		 doName: ttitem
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmitem", dsName="wicketds.server.dmitem", dsId="daitem", daoId="ttitem", isLocked=false)
public class ItemDataObject extends DataObjectAdaptor<Item> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1391676742820L;
		
	@Generated
	@Deprecated
	public ItemDataObject (IAppConnector connector) {
		super(connector, new ItemDSSchema(), new ItemSchema());
	}

	@Generated
	public ItemDataObject (IConfig config, String appName) {
		super(config, appName, new ItemDSSchema(), new ItemSchema());
	}

	@Generated
	@Deprecated
	public ItemDataObject (IAppConnector connector, IDSSchema dsSchema, IDAOSchema<Item> daoSchema ) {
		super(connector, dsSchema, daoSchema);
	}

	@Generated
	public ItemDataObject (IConfig config, String appName, IDSSchema dsSchema, IDAOSchema<Item> daoSchema ) {
		super(config, appName, dsSchema, daoSchema);
	}
	
}

