package net.quarix.qrx4j.samples.data.dao;

import net.quarix.qrx4j.samples.data.beans.meta.PurchaseOrderSchema;
import net.mystrobe.client.connector.quarixbackend.Generated;
import net.mystrobe.client.connector.IConfig;
import net.mystrobe.client.connector.IAppConnector;
import net.quarix.qrx4j.samples.data.beans.PurchaseOrder;
import net.quarix.qrx4j.samples.data.beans.meta.PurchaseOrderDSSchema;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmpurchaseorder
 *		 doName: ttpurchaseorder
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmpurchaseorder", dsName="wicketds.server.dmpurchaseorder", dsId="daopurchaseorder", daoId="ttpurchaseorder", isLocked=false)
public class PurchaseOrderDataObject extends DataObjectAdaptor<PurchaseOrder> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1391676813130L;
		
	@Generated
	@Deprecated
	public PurchaseOrderDataObject (IAppConnector connector) {
		super(connector, new PurchaseOrderDSSchema(), new PurchaseOrderSchema());
	}

	@Generated
	public PurchaseOrderDataObject (IConfig config, String appName) {
		super(config, appName, new PurchaseOrderDSSchema(), new PurchaseOrderSchema());
	}

	@Generated
	@Deprecated
	public PurchaseOrderDataObject (IAppConnector connector, IDSSchema dsSchema, IDAOSchema<PurchaseOrder> daoSchema ) {
		super(connector, dsSchema, daoSchema);
	}

	@Generated
	public PurchaseOrderDataObject (IConfig config, String appName, IDSSchema dsSchema, IDAOSchema<PurchaseOrder> daoSchema ) {
		super(config, appName, dsSchema, daoSchema);
	}
	
}

