package net.quarix.qrx4j.samples.data.dao;

import net.mystrobe.client.connector.quarixbackend.Generated;
import net.quarix.qrx4j.samples.data.beans.meta.SalesRepSchema;
import net.mystrobe.client.connector.IConfig;
import net.quarix.qrx4j.samples.data.beans.meta.SalesRepDSSchema;
import net.mystrobe.client.connector.IAppConnector;
import net.quarix.qrx4j.samples.data.beans.SalesRep;
import net.mystrobe.client.connector.quarixbackend.GeneratorMeta;
import net.mystrobe.client.IDAOSchema;
import java.io.Serializable;
import net.mystrobe.client.IDSSchema;
import net.mystrobe.client.DataObjectAdaptor;

/**
 *
 * This class was generated by net.mystrobe.client.connector.quarixbackend.ClassGenerator
 *
 * Used parameters:
 *		appName: mystrobe
 *		 dsName: wicketds.server.dmsalesrep
 *		 doName: ttsalesrep
 *
 */

@GeneratorMeta(appName="mystrobe", urn="wicketds.server.dmsalesrep", dsName="wicketds.server.dmsalesrep", dsId="daosalesrep", daoId="ttsalesrep", isLocked=false)
public class SalesRepDataObject extends DataObjectAdaptor<SalesRep> implements Serializable {

	@Generated
	private static final long serialVersionUID = 1391676865683L;
		
	@Generated
	@Deprecated
	public SalesRepDataObject (IAppConnector connector) {
		super(connector, new SalesRepDSSchema(), new SalesRepSchema());
	}

	@Generated
	public SalesRepDataObject (IConfig config, String appName) {
		super(config, appName, new SalesRepDSSchema(), new SalesRepSchema());
	}

	@Generated
	@Deprecated
	public SalesRepDataObject (IAppConnector connector, IDSSchema dsSchema, IDAOSchema<SalesRep> daoSchema ) {
		super(connector, dsSchema, daoSchema);
	}

	@Generated
	public SalesRepDataObject (IConfig config, String appName, IDSSchema dsSchema, IDAOSchema<SalesRep> daoSchema ) {
		super(config, appName, dsSchema, daoSchema);
	}
	
}

